import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import Head from "next/head";
import NavBar from "@/components/NavBar";
import SessionProvider from "@/utils/SessionProvider";
import {getServerSession} from "next-auth";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  manifest:"/manifest.json",
  title: "Pokemon",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await getServerSession()
  
  return (
    <html lang="en">
      <Head>
        <title>Pokemon Data</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body
        className={cn(
          "bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        {/* <header className="header">
          <h5>Pokemon Search App</h5>
        </header> */}
        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl text2xl gap-2 mb-10">
            <NavBar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
